### PR TITLE
Add aleth-bootnode readme

### LINKED ISSUE #5385: Create aleth-bootnode documentation
aleth-bootnode was committed in this PR: #5378 

Some basic documentation should be authored which covers its purpose, command-line arguments, and any outstanding issues.

### PR DESCRIPTION
**Pull request by halfalicious**
Fix #5385 

Add a README file for aleth-bootnode

### CODE REVIEW

**Comment by halfalicious** [comment]
@gumb0 / @chfast Not sure if we want to link to this README in the Aleth README? Perhaps we can add a "tools" section and link to it? 

Also, aleth-bootnode doesn't have any version information - do we want to add this?

**Review by gumb0 — CHANGES_REQUESTED** [review]
We could make it better conform to Standard Readme by

- Adding short summary starting with `>` before long description https://github.com/RichardLitt/standard-readme/blob/master/spec.md#short-description
- Renaming `Getting Aleth-bootnode` to `Install`
- Adding `Contributing` and `License` sections - those can just refer to existing files

Also I'm not sure about placing it in this folder, will anyone notice it there? Maybe the link from the big readme would help, yes.

**Comment by halfalicious** [comment]
@gumb0: Ah, didn’t realize there was a standard readme format. Will update with your suggestions

**Review by gumb0 — APPROVED** [review]

**Comment by halfalicious** [comment]
@gumb0 Thanks for adding the rlp and testeth tools and updating the aleth-vm description!

**Pull request merged**
