### PR TITLE
EIP-2384 Difficulty Bomb Delay / Muir Glacier fork

### PR DESCRIPTION
**Pull request by gumb0**
https://eips.ethereum.org/EIPS/eip-2384
https://eips.ethereum.org/EIPS/eip-2387

### CODE REVIEW

**Comment by winsvega** [comment]
Muir Glacier? I thought after Berlin should come London

**Comment by gumb0** [comment]
@winsvega This is _before_ Berlin actually

**Comment by winsvega** [comment]
Omg, who has come up with such a name

**Comment by chfast** [comment]
Do we want to release it as 1.8.0?

**Comment by gumb0** [comment]
@chfast Yes, I think we should

**Comment by chfast** [comment]
Anything is blocking 1.8.0 release?

**Comment by gumb0** [comment]
@chfast nothing that I know of, I think we can release

**Pull request merged**
