### PR TITLE
Implement EIP-1884: Repricing for trie-size-dependent opcodes in aleth-interpreter

### PR DESCRIPTION
**Pull request by gumb0**
https://eips.ethereum.org/EIPS/eip-1884

It includes SELFBALANCE implementation; opcode repricing is enabled automagically via EVMC instruction metrics.

### CODE REVIEW

**Comment by halfalicious** [comment]
> 
> 
> https://eips.ethereum.org/EIPS/eip-1884
> 
> It includes SELFBALANCE implementation; opcode repricing is enabled automagically via EVMC instruction metrics.
> 
> PR is currently based on [LegacyVM implementation](https://github.com/ethereum/aleth/pull/5700) because of dependency on unit tests.

Where is the automagic opcode pricing done in EVMC?

**Comment by halfalicious** [comment]
Presumably the other PR which implements 1884 in LegacyVM is now redundant (https://github.com/ethereum/aleth/pull/5700)?

**Comment by halfalicious** [comment]
Is this ready for review? Looked at the feature changes and they look fine, still need to take a look at the tests.

**Comment by gumb0** [comment]
@halfalicious It will be ready after rebase

**Comment by gumb0** [comment]
@halfalicious `instructions` lib in EVMC provides costs for all opcodes on all revisions
https://github.com/ethereum/evmc/blob/master/include/evmc/instructions.h

**Comment by halfalicious** [comment]
> 
> 
> @halfalicious `instructions` lib in EVMC provides costs for all opcodes on all revisions
> https://github.com/ethereum/evmc/blob/master/include/evmc/instructions.h

@gumb0 Ah thank you!

**Pull request merged**
