### PR TITLE
move dockerfiles to root

### PR DESCRIPTION
**Pull request by holiman**
I think this solves the problem of building on docker hub, as discussed in https://github.com/ethereum/aleth/pull/5344

### CODE REVIEW

**Comment by holiman** [comment]
Ping @chfast

**Comment by chfast** [comment]
I believe it was working before, just Docker Hub was not able to finish the build (no errors reported, probably out-of-memory).

**Comment by holiman** [comment]
I don't think so.. Could we please then make copies of at least one of the files into the root, so I can try it out?

**Comment by chfast** [comment]
Done.

**Comment by holiman** [comment]
Interesting.. So this 'works' -- docker hub now does not fail on an early stage, instead it builds for two hours, and then aborts the build.

**Comment by chfast** [comment]
Well, I believe I had similar behavior when the docker file was specified as `scripts/docker/aleth.dockerfile`.

Anyway, seems it is too heavy for Docker Hub. I can have it done on Circle CI, but I have to figure out how to build them (aleth and testeth) once.

**Comment by holiman** [comment]
Build them both into an `alltools`image, then use a multistage build to just pick out the cherries from `alltools`?

**Comment by chfast** [comment]
The automation seems to be working. You can test `ethereum/testeth:20181122` docker image.

**Pull request closed without merging**
