### PR TITLE
Implement EIP-2200: Structured Definitions for Net Gas Metering in aleth-interpreter

### PR DESCRIPTION
**Pull request by gumb0**
https://github.com/ethereum/EIPs/pull/2200

### CODE REVIEW

**Comment by winsvega** [comment]
waiting this PR to update the blockchain tests and check aleth consensus with geth and besu

**Comment by payvint** [comment]
Hi guys, could you please explain me where is this constants are located?
https://gist.github.com/karalabe/adc43c07db9f03be82093cd5466562b0#specification
I have a little bit got lost in code

**Comment by gumb0** [comment]
@payvint there might be not exact one-to-one correspondence between the constants in the spec and constants defined in our code, but for LegacyVM they are in https://github.com/ethereum/aleth/blob/master/libethcore/EVMSchedule.h
and for aleth-interpreter they are in https://github.com/ethereum/aleth/blob/master/libaleth-interpreter/VM.h

**Comment by gumb0** [comment]
@payvint Our implementation I think is closer to the spec definition in the current version of the EIP at https://github.com/ethereum/EIPs/pull/2200, than to the one at your link (but I guess they are effectively equivalent)

**Comment by payvint** [comment]
Thanks @gumb0, I will take a look

**Comment by payvint** [comment]
So, @gumb0 , thank you for links very much. I 've just figured it out. But I have one question:
https://gist.github.com/karalabe/adc43c07db9f03be82093cd5466562b0#specification
ethereum/EIPs#2200
In last version - constants are changed and optimized from 8 new to 1 changes in existing implementation, but you changed a constant named SLOAD_GAS - does it related to existence one?
SLOAD_GAS was 200 and became 800 - does it mean that opcode sload - costs 4 times more?
if yes - it is not mentioned in EIP, as I read. if no - please show me where could I find proofs?:)
Thanks

**Comment by gumb0** [comment]
@payvint that's right, SLOAD cost has changed, and it's the subject of another Istanbul EIP https://eips.ethereum.org/EIPS/eip-1884

**Comment by payvint** [comment]
@gumb0 Thank you very much. Figured out everything!!!

**Pull request merged**
