### PR TITLE
Upgrade GTest to 1.8.1

### PR DESCRIPTION
**Pull request by moneroexamples**
Related issues are:
https://github.com/ethereum/aleth/issues/5790
https://github.com/ethereum/aleth/issues/5637

### CODE REVIEW

**Comment by halfalicious** [comment]
Failed tests were networking tests which may have reliability issues - kicked off re-runs

**Comment by halfalicious** [comment]
@moneroexamples Is this ready for review?

**Comment by moneroexamples** [comment]
yes, I don't plan changes to this PR unless required. The aleth still wont build on arch linux due to this https://github.com/ethereum/aleth/issues/5795, but I think its better to work on the new issue once gtest get's sorted out.

**Comment by chfast** [comment]
Also please see https://github.com/ethereum/aleth/pull/5798 for GCC9 related fixes.

**Pull request merged**
